# Generated by Django 5.2.17 on 2026-09-29 18:41

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_id',
            field=models.CharField(db_index=True, default=apps.accounts.models.generate_customer_id, editable=False, max_length=12, unique=True),
        ),
    ]
