# Generated by Django 5.2.17 on 2026-09-29 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0002_alter_order_options_order_inventory_committed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltyentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loyaltyentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loyalty_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltyentry',
            name='entry_type',
            field=models.CharField(choices=[('EARN', 'Earn'), ('REDEEM', 'Redeem'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], db_index=True, default='EARN', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyaltyentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_entries', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='loyaltyentry',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='loyaltyentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loyaltyentry',
            index=models.Index(fields=['user', 'created_at'], name='loyalty_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyentry',
            index=models.Index(fields=['user', 'entry_type'], name='loyalty_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltyentry',
            index=models.Index(fields=['order', 'entry_type'], name='loyalty_order_type_idx'),
        ),
    ]
