# Generated by Django 5.2.17 on 2026-09-29 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_inventory_committed_and_more'),
        ('promotions', '0001_initial'),
        ('stores', '0002_storestaffmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='promotion',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of times one user can redeem this promotion.'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a platform-wide promotion.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions. Leave empty for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promo_active_period_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['store', 'is_active'], name='promo_store_active_idx'),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemption', to='orders.order'),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.promotion'),
        ),
        migrations.AddField(
            model_name='promotionredemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'user'], name='promo_redemption_user_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=models.Index(fields=['promotion', 'created_at'], name='promo_redemption_time_idx'),
        ),
    ]
