# Generated by Django 5.2.17 on 2026-09-28 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinventory',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storeinventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['store', 'is_available'], name='inventory_store_available_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinventory',
            index=models.Index(fields=['product'], name='inventory_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='storeinventory',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_reserved_not_above_quantity'),
        ),
    ]
