# Generated by Django 5.2.17 on 2026-09-29 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storeinventory_reserved_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('RESERVATION', 'Reservation'), ('RESERVATION_RELEASE', 'Reservation Release'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('quantity_change', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('reserved_before', models.PositiveIntegerField(default=0)),
                ('reserved_after', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.storeinventory')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inventory', 'created_at'], name='inv_move_inventory_time_idx'), models.Index(fields=['movement_type', 'created_at'], name='inv_move_type_time_idx')],
            },
        ),
    ]
