# Generated by Django 5.2.17 on 2026-09-29 19:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_inventory_committed_and_more'),
        ('stores', '0002_storestaffmembership'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('is_staff_reply', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CUSTOMER', 'Waiting for Customer'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('ORDER', 'Order'), ('PAYMENT', 'Payment'), ('DELIVERY', 'Delivery'), ('REFUND', 'Refund'), ('PRODUCT', 'Product'), ('ACCOUNT', 'Account'), ('PROMOTION', 'Promotion'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='orders.order'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CUSTOMER', 'Waiting for Customer'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='supp_ticket_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['store', 'status'], name='supp_ticket_store_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'created_at'], name='supp_ticket_user_idx'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.supportticket'),
        ),
        migrations.AddField(
            model_name='supportstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportstatushistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='support.supportticket'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='supp_msg_ticket_idx'),
        ),
        migrations.AddIndex(
            model_name='supportstatushistory',
            index=models.Index(fields=['ticket', 'created_at'], name='supp_hist_ticket_idx'),
        ),
    ]
