# Generated by Django 5.2.17 on 2026-09-28 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStaffMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='storestaff_user_active_idx'), models.Index(fields=['store', 'is_active'], name='storestaff_store_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='unique_store_staff_membership')],
            },
        ),
    ]
